"""Add difficulty to questions

Revision ID: e58ba69dd1ab
Revises:
Create Date: 2025-09-20 20:19:41.031732

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e58ba69dd1ab"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("user_quiz_attempt")
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "difficulty", sa.String(20), nullable=False, server_default="Easy"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.drop_column("difficulty")

    op.create_table(
        "user_quiz_attempt",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("quiz_id", sa.INTEGER(), nullable=True),
        sa.Column("question_order", sa.TEXT(), nullable=True),
        sa.Column("timestamp", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quiz.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
